[package]
name = "tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = { version = "0.30.0", features = ["unstable-widget-ref"] }
ratatui-widgets = "0.3.0"
serde = { version = "1.0.228", features = [ "derive" ] }
serde_yaml = "0.9.34"
